
eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    preferSameZoneEureka: true
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-us:9000/eureka/
