
spring:
  profiles: default
server:
  port: 9000
eureka:
  instance:
    hostname: my-eureka-server.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---

spring:
  profiles: united-states
  application:
    name: eureka-server-clustered
server:
  port: 9000
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-fr:${server.port}/eureka/,http://eureka-vn:${server.port}/eureka/
  server:
    enableSelfPreservation: false

---

spring:
  profiles: france
  application:
    name: eureka-server-clustered
server:
  port: 9000
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-us:${server.port}/eureka/,http://eureka-vn:${server.port}/eureka/
  server:
    enableSelfPreservation: false

---

spring:
  profiles: vietnam
  application:
    name: eureka-server-clustered
server:
  port: 9000
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-us:${server.port}/eureka/,http://eureka-fr:${server.port}/eureka/
  server:
    enableSelfPreservation: false
